# Generated by Django 2.2.1 on 2019-05-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
